import Head from 'next/head';

import { About, Footer, Formulas, GroceryStore, Header, Menu } from '../components';

export default function Home() {
  return (
    <>
      <Head>
        <title>{"Restaurant Goût d'ouest"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      </Head>
      <main>
        <Header />
        <About />
        <Formulas />
        <Menu />
        <GroceryStore />
        <Footer />
      </main>
    </>
  );
}
